config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :celebrities

end

app/models/celebrity.rb
class Celebrity < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/celebrities_controller.rb
class CelebritiesController < ApplicationController

  def index
    @celebrity = Celebrity.new
    @celebrities = Celebrity.all
  end

  def create
    @celebrity = Celebrity.create(celebrity_params)
    if @celebrity.save
      redirect_to celebrities_path
    else
      render :index
    end
  end

  def show
    @celebrity = Celebrity.find(params[:id])
  end

  def edit
    @celebrity = Celebrity.find(params[:id])
  end

  def update
    @celebrity = Celebrity.find(params[:id])
    @celebrity.update_attributes!(celebrity_params)
    redirect_to celebrities_path
  end

  def destroy
    @celebrity = Celebrity.find(params[:id]).delete
    redirect_to celebrities_path

  end

  private
  def celebrity_params
    params.require(:celebrity).permit(:name, :job)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/celebrities/edit.html.erb
<%= form_for @celebrity do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :job %>
    <%= f.text_field :job %>
  </p>
  <p>
  <%= f.submit 'Update celebrity' %>
  </p>
<% end %>

app/views/celebrities/index.html.erb
<%= form_for @celebrity do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :job %>
    <%= f.text_field :job %>
  </p>
  <%= f.submit 'Add celebrity' %>
<% end %>

<% @celebrities.each do |celebrity| %>
<ul>
  <li>
    <%= link_to "#{celebrity.name}", celebrity_path(celebrity) %>, <%= celebrity.job %>
  </li>
</ul>
<% end %>

app/views/celebrities/show.html.erb
<ul>
  <li>
    <%= @celebrity.name %>, <%= @celebrity.job %>
  </li>
</ul>

<%= link_to 'Edit', edit_celebrity_path(@celebrity) %>
<%= link_to 'Delete celebrity', celebrity_path(@celebrity), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudCelebrities</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Welcome</h2>

<%= link_to 'Add a celebrity', celebrities_path %>